############################
#          World           #
############################
world:
  # How much fall damage will players get? only 0 or positive values
  fall-damage-multiplier: 0.5

  # Changes default walking speed [Minecraft default is 0.2]
  default-player-speed: 0.18

  # Should players get hungry? [Default: true]
  hunger: false
  
  # How much % of experience player loses on death [Default: 0.1 | 0.0 - 1.0]
  exp-lose: 0.1

############################
#          Combat          #
############################
combat:
  # if true players can hit headshot to any mob or player
  allow-headshots: true

  # works only when 'allow-headshots' is true
  # changes the amount of damage entity gets when headshotted
  headshot-multiplier: 0.25


############################
#       Announcements      #
############################
announce:
  # Should we announce that new player joined?
  first-join: true
  first-join-message: "&dGracz {PLAYER} wszedl na serwer po raz pierwszy!"
  
  # player joined of left the game, yay! lets configure this shitty spam message :d
  join: true
  join-message: "(green){PLAYER} (bold)+"
  
  left: true
  left-message: "(red){PLAYER} (bold)-"


############################
#           Chat           #
############################
chat:
  # should chat be blocked for new players?
  restrict: true
  
  # Minimal lvl needed to send messages in chat
  lvl-min: 10
  
  # message when player has too low level
  low-lvl-message: "(red)Musisz miec conajmniej {LEVEL_MIN} poziom by uzywac chatu!"
  
  # chat messages format, how message looks like
  message-format: "(gray)&l[&6{LEVEL}&7&l]-&a&l{GROUP}&7&l-&6{PLAYER}&7&l:&f {MESSAGE}"
  
  # These colors are being used in messages sent to players in various occasions like missing permissions or too low money etc.
  info-color: "&6"
  warn-color: "&e"
  error-color: "&4"
  other-color: "&a&l"
  ping-color: "&d"


############################
#         Economy          #
############################
economy:
  currency-symbol: "$"


############################
#       Protection         #
############################
# this allows you to protect world from griefing or prevent players from going into prohibited places
protect:
  explosions:
    enabled: true
    drop: true
    # chance to get block after explosion [0 - 1]
    drop-rate: 1
    worlds:
        - world
    # how fast block renews after explosion
    time: 1
  floor-check:
    enabled: true
    blocks:
        - torch
        - barrier
        

############################
#  Other bu ... features   #
############################
other:
  real-time:
    enabled: true
    # in seconds
    interval: 300
    weather:
      enabled: true
      city: Warsaw
      api-key:
    time:
      enabled: true