fall-damage-multiplier: 2.5
default-player-speed: 0.18

database:
  host: ""
  name: ""
  username: ""
  password: ""
  port: 3306
  
announce:
  first-join: true
  first-join-message: "&dGracz  {PLAYER}  wszedl na serwer po raz pierwszy!"
  
  join: true
  join-message: " (green)  {PLAYER} +"
  
  left: true
  left-message: " (red)  {PLAYER} -"

chat:
  restrict-chat: true
  chat-lvl-min: 10
  chat-low-lvl-message: " (red) Musisz mieæ conajmniej  {LEVEL_MIN}  poziom by uzywac chatu!"
  chat-message-format: " (orange) [&7 {LEVEL} &6]&6  {PLAYER} :&f  {MESSAGE} "
    
  info-color: "&6"
  warn-color: "&e"
  error-color: "&4"
  other-color: "&a&l"
  
levels:
  count: 15
  1: 100
  2: 250
  3: 500
  4: 750
  5: 1000
  6: 1400
  7: 1850
  8: 2300
  9: 2800
  10: 3300
  11: 3800
  12: 4400
  13: 5000
  14: 5750
  15: 6750
  
economy:
  currency-symbol: "$"
  
other:
  chest-log:
    enabled: false
    format: "Gracz  {PLAYER}  Otworzyl skrzynie na koordynatach  {WORLD}  {X}  {Y}  {Z}"
protect:
  explosions:
    enabled: true
    drop: true
    drop-rate: 1
    worlds:
        - system_spawn