version: 1.3a
#+============================+
#|############################|
#|#       Announcements      #|
#|############################|
#+============================+
announce:
  # should plugin use this module? [Default: true]
  enabled: true
  
  # Should we announce that new player joined?
  first-join: true
  first-join-message: "&dGracz {PLAYER} wszedl na serwer po raz pierwszy!"
  
  # player joined of left the game, yay! lets configure this shitty spam message :d
  join: true
  join-message: "(green){PLAYER} (bold)+"
  
  left: true
  left-message: "(red){PLAYER} (bold)-"

#+============================+
#|############################|
#|#           Chat           #|
#|############################|
#+============================+
chat:
  # should plugin use this module? [Default: true]
  enabled: true

  # should chat be blocked for new players?
  restrict: true
  
  # Block messages with swear words? [Default: true]
  censor: true
  
  # Minimal lvl needed to send messages in chat [Default: 10]
  lvl-min: 10
  
  # message when player has too low level
  low-lvl-message: "(red)Musisz miec conajmniej {LEVEL_MIN} poziom by uzywac chatu!"
  
  # chat messages format, how message looks like
  message-format: "{WORLD_TYPE}(gray)&l[&6{LEVEL}&7&l]-&a&l{GROUP}&7&l-&6{PLAYER}&7&l:&f {MESSAGE}"
  
  # These colors are being used in messages sent to players in various occasions like missing permissions or too low money etc.
  info-color: "&6"
  warn-color: "&e"
  error-color: "&4"
  other-color: "&a&l"
  ping-color: "&d"

  # Can Players ping other players on chat? [Default: true]
  allow-pings: true

#+============================+
#|############################|
#|#          Combat          #|
#|############################|
#+============================+
combat:
  # should plugin use this module? [Default: true]
  enabled: true
  
  # if true players can hit headshot to any mob or player
  # [Default: true]
  allow-headshots: true

  # changes the amount of damage entity gets when headshotted
  # [Default: 1.25]
  headshot-multiplier: 1.25
  
  # prevents players from logging out while in combat
  # [Default: true, 15.0]
  combat-log: true
  combat-log-time: 15.0
  # do not drop items on the floor when player disconnects in combat. take them to the void where all players can take them from
  # [Default: false] | still not working
  combat-log-items-void: false
  
  # do players drop money on death?
  money-drop:
    enabled: true
    # if true money is not directly sent to killer, but it is dropped as item instead
    item: true
    # should we remove money from dead player?
    remove: true
    # how much money players lose on death
    count: 50
    # how much % of money players drop on death [Default: 0.0 | (ignore)0.0 - 1.0(all money) ]
    percent: 0.0
    # how much more money do players drop for suicide? [Default: 1.5]
    suicide-multiplier: 1.5
    
#+============================+
#|############################|
#|#         Commands         #|
#|############################|
#+============================+
commands:
  teleportation-cooldown: 10
  teleportation-invulnerability: 2

#+============================+
#|############################|
#|#         Economy          #|
#|############################|
#+============================+
economy:
  # should plugin use this module? [Default: true]
  enabled: true
  # This players will get at first join [Default:69]
  start-balance: 69
  
  currency-symbol: "$"

#+============================+
#|############################|
#|#         Leveling         #|
#|############################|
#+============================+
leveling:
  # should plugin use this module? [Default: true]
  enabled: true

  # How much % of plugin experience player loses on death [Default: 0.1 | 0.0 - 1.0]
  exp-lose: 0.1
  
  # Convert minecraft experience to plugin experience? [Default: true]
  convert-exp: true

#+============================+
#|############################|
#|#         Players          #|
#|############################|
#+============================+
players:
  # How much profiles do players have? || they can switch between them by /profile [/prof]
  # [Default: 1]
  max-profiles: 1
  
  # Does players get hungry? [Default: true]
  hunger: true
  
  # How fast does players get hungry? [Default: 1.0 | 0.0 - infinity]
  hunger-multiplier: 1.0
  
  # how strong is food? [Default: 1.0]
  feed-multiplier: 1.0
  
  # Changes default walking speed [Minecraft default is 0.2 | Plugin Default: 0.18]
  default-player-speed: 0.18
  
  # Can players respawn in their bed or should they whole time respawn on main spawn?
  # [Default: true]
  bed-respawn: true

#+============================+
#|############################|
#|#       Protection         #|
#|############################|
#+============================+
# this allows you to protect world from griefing or prevent players from going into prohibited places
protect:
  # should plugin use this module? [Default: true]
  enabled: true
  
  explosions:
    enabled: true
    drop: true
    # chance to get block after explosion [0 - 1]
    drop-rate: 1
    worlds:
        - world
    # how fast block renews after explosion
    time: 1
  floor-check:
    enabled: true
    blocks:
        - torch
        - barrier

#+============================+
#|############################|
#|#          World           #|
#|############################|
#+============================+
world:
  # should plugin use this module? [Default: true]
  enabled: true
  
  # How much fall damage will players/entities get? only 0 or positive values [Default: 1.25]
  fall-damage-multiplier: 1.25
  
  # Should mobs drop items? [Default: true]
  mob-drop: true

  # Should mobs drop minecraft experience? [Default: true]
  mob-vanilla-exp: true
  
  # Mob minecraft experience drop multiplier [Default: 1.0]
  mob-vanilla-exp-multiplier: 1.0
  
  # Defines if players should respawn in world they died or normally.
  # Overrides bed-respawn if player died in other world than his bed is in and this list contains his death world.
  respawn-worlds:
      - world
      - world_nether

#+============================+
#|############################|
#|#  Other bu ... features   #|
#|############################|
#+============================+
other:
  easter-eggs: false
  
# Still Nothing Here