core:
  announce:
    first-join: true
    first-join-message: "Gracz PLAYER wszedl na serwer po raz pierwszy!"
    
    join: true
    join-message: "PLAYER +"
    
    left: true
    left-message: "PLAYER -"
    
  info-color: "&6"
  warn-color: "&e"
  error-color: "&4"
  other-color: "&a&l"
  
  fall-damage-multiplier: 2.5
  
addons:
  klasy:
    enabled: true
    level:
      lvl-start: 1
      lvl-max: 7

  items:
    enabled: true
    stats:
      lifesteal: true
  messages:
    disabled: "To rozszerzenie zostalo chwilowo wylaczone!"