name: RPGcore
main: com.rpg.core.Main
version: 1.3.2.5
api-version: 1.16
authors: [_woody44_, damian5466]
database: true

softdepend:
    - PermissionsEx
depend:
    - AuthMe
commands:
  money:
    description: Sprawdz stan swego konta.
    permission: RPG.core.eco.money
    usage: /money
  pay:
    description: Przelej pieniadze znajomemu
    permission: RPG.core.eco.pay
    usage: /pay <player> <count>
  system:
    description: Informacje na temat pluginu.
    permission: RPG.core.system
    usage: /system
  reloadconfig:
    description: Pozwala przeladowac ponownie konfiguracje pluginu bez wymogu restartu serwera.
    permission: RPG.core.reload
    usage: /reloadconfig
  locationcreate:
    description: Tworzy Nowa lokacje w miejscu w ktorym stoisz w kieunku w ktorym sie patrzysz.
    permission: RPG.core.locationcreate
    usage: /locationcreate <name>
  locationdelete:
    description: Usuwa lokacje zapisana w bazie danych pod podana nazwa.
    permission: RPG.core.locationdelete
    usage: /locationdelete <name>
  locationtp:
    description: Teleportuje do wczesniej zapisanej lokacji.
    permission: RPG.core.locationtp
    usage: /locationtp <name>
    
load: POSTWORLD
loadbefore:
  - RPGitems
  - RPGKlasy
  - RPGSideMode

description: Podstawa dla pluginow zwiazanych z systemem RPG.