name: RPGcore
main: com.rpg.core.Main
version: 1.2.6
api-version: 1.15
authors: [_woody44_, damian5466]
database: true

softdepend:
    - PermissionsEx
depend:
    - AuthMe
commands:
  money:
    description: Sprawdz stan swego konta.
    permission: RPG.core.eco.money
    usage: /money
  pay:
    description: Przelej pieniadze znajomemu
    permission: RPG.core.eco.pay
    usage: /pay <player> <count>
  system:
    description: Informacje na temat pluginu.
    permission: RPG.core.system
    usage: /system
  reloadconfig:
    description: Pozwala przeladowac ponownie konfiguracje pluginu bez wymogu restartu serwera.
    permission: RPG.core.reload
    usage: /reloadconfig
load: STARTUP

description: Podstawa dla pluginow zwiazanych z systemami RPG.