name: RPGcore
main: com.rpg.core.Main
version: 1.1.4
api-version: 1.15
softdepend:
    - PermissionsEx
depend:
    - AuthMe
commands:
  money:
    description: Sprawdz stan swego konta.
  pay:
    description: Przelej pieniadze znajomemu
  system:
    description: Informacje na temat pluginu
load: STARTUP